import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
       <Head>
        <title>Succour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Favicon.svg" />
      </Head>
        
         <Component {...pageProps} />

    </>
  )

}

export default MyApp
