# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoRide-Passenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoRide-Passenger
  pod 'GeoFire', '~> 4.0'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'drawer-view', '~> 1.0.4'
  pod 'web3swift'

  target 'CryptoRide-PassengerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoRide-PassengerUITests' do
    # Pods for testing
  end

end
