/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ActionDone = ContractEventLog<{
  status: boolean;
  statement: string;
  0: boolean;
  1: string;
}>;

export interface EmitsEvent extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): EmitsEvent;
  clone(): EmitsEvent;
  methods: {};
  events: {
    ActionDone(cb?: Callback<ActionDone>): EventEmitter;
    ActionDone(options?: EventOptions, cb?: Callback<ActionDone>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "ActionDone", cb: Callback<ActionDone>): void;
  once(
    event: "ActionDone",
    options: EventOptions,
    cb: Callback<ActionDone>
  ): void;
}
