/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AccountInterface extends ethers.utils.Interface {
  functions: {
    "added(address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balances(address,uint8)": FunctionFragment;
    "clearSubscription(uint256)": FunctionFragment;
    "depositERC20Token(address,uint256)": FunctionFragment;
    "erc20Balances(address)": FunctionFragment;
    "getSpendableBalance(address)": FunctionFragment;
    "getSubscriptionInfo(uint256)": FunctionFragment;
    "initializeInfo(tuple,bool,bool,uint256,uint256,address,address)": FunctionFragment;
    "manager()": FunctionFragment;
    "owner()": FunctionFragment;
    "rekey(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setStatus(uint256,bool,bool)": FunctionFragment;
    "split(uint256,address,address[],address,uint256,uint256)": FunctionFragment;
    "subscriptionInfo(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateBalancesInUse(address,uint256,bool)": FunctionFragment;
    "updateTurnTime(uint256)": FunctionFragment;
    "withdrawERC20TokenOnlyOwner(address,uint256)": FunctionFragment;
    "withdrawRouterOnly(address,address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "added", values: [string]): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clearSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20Token",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "erc20Balances",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpendableBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeInfo",
    values: [
      {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      boolean,
      boolean,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rekey", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setStatus",
    values: [BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [BigNumberish, string, string[], string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBalancesInUse",
    values: [string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTurnTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20TokenOnlyOwner",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRouterOnly",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "added", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20Balances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpendableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rekey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBalancesInUse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTurnTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20TokenOnlyOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRouterOnly",
    data: BytesLike
  ): Result;

  events: {
    "AccountLaunched(address,address)": EventFragment;
    "BandCreated(uint256,tuple)": EventFragment;
    "GetFinanced(uint256,uint256,address)": EventFragment;
    "Joined(uint256,address,uint256)": EventFragment;
    "NewAccount(address,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Payback(uint256,uint256,address)": EventFragment;
    "Rekeyed(address,address)": EventFragment;
    "RoundUp(uint256,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountLaunched"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BandCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GetFinanced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Joined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewAccount"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Payback"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rekeyed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoundUp"): EventFragment;
}

export class Account extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AccountInterface;

  functions: {
    added(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "added(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    approve(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balances(address,uint8)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    clearSubscription(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "clearSubscription(uint256)"(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    depositERC20Token(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "depositERC20Token(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    erc20Balances(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<{
      _balances: BigNumber;
      0: BigNumber;
    }>;

    "erc20Balances(address)"(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<{
      _balances: BigNumber;
      0: BigNumber;
    }>;

    getSpendableBalance(
      token: string,
      overrides?: CallOverrides
    ): Promise<{
      _withdrawable: BigNumber;
      _engaged: BigNumber;
      _mostRecent: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    "getSpendableBalance(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<{
      _withdrawable: BigNumber;
      _engaged: BigNumber;
      _mostRecent: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    getSubscriptionInfo(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        position: BigNumber;
        payDate: BigNumber;
        turnTime: BigNumber;
        owings: BigNumber;
        reward: BigNumber;
        colBals: BigNumber;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: boolean;
        7: boolean;
        8: boolean;
      };
    }>;

    "getSubscriptionInfo(uint256)"(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        position: BigNumber;
        payDate: BigNumber;
        turnTime: BigNumber;
        owings: BigNumber;
        reward: BigNumber;
        colBals: BigNumber;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: boolean;
        7: boolean;
        8: boolean;
      };
    }>;

    initializeInfo(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initializeInfo((uint256,uint256,uint256,uint256,uint256,uint256,bool,bool,bool),bool,bool,uint256,uint256,address,address)"(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    manager(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "manager()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    rekey(
      newAccount: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "rekey(address)"(
      newAccount: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setStatus(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setStatus(uint256,bool,bool)"(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    split(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "split(uint256,address,address[],address,uint256,uint256)"(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    subscriptionInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      position: BigNumber;
      payDate: BigNumber;
      turnTime: BigNumber;
      owings: BigNumber;
      reward: BigNumber;
      colBals: BigNumber;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
      7: boolean;
      8: boolean;
    }>;

    "subscriptionInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      position: BigNumber;
      payDate: BigNumber;
      turnTime: BigNumber;
      owings: BigNumber;
      reward: BigNumber;
      colBals: BigNumber;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
      7: boolean;
      8: boolean;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateBalancesInUse(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateBalancesInUse(address,uint256,bool)"(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateTurnTime(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateTurnTime(uint256)"(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawERC20TokenOnlyOwner(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawERC20TokenOnlyOwner(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawRouterOnly(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawRouterOnly(address,address,address,uint256,uint256)"(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  added(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "added(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  approve(
    erc20Address: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    erc20Address: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balances(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "balances(address,uint8)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  clearSubscription(
    poolId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "clearSubscription(uint256)"(
    poolId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  depositERC20Token(
    erc20Address: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "depositERC20Token(address,uint256)"(
    erc20Address: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  erc20Balances(
    erc20Address: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "erc20Balances(address)"(
    erc20Address: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSpendableBalance(
    token: string,
    overrides?: CallOverrides
  ): Promise<{
    _withdrawable: BigNumber;
    _engaged: BigNumber;
    _mostRecent: BigNumber;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
  }>;

  "getSpendableBalance(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<{
    _withdrawable: BigNumber;
    _engaged: BigNumber;
    _mostRecent: BigNumber;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
  }>;

  getSubscriptionInfo(
    poolId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    position: BigNumber;
    payDate: BigNumber;
    turnTime: BigNumber;
    owings: BigNumber;
    reward: BigNumber;
    colBals: BigNumber;
    isAdmin: boolean;
    isMember: boolean;
    hasGH: boolean;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: boolean;
    7: boolean;
    8: boolean;
  }>;

  "getSubscriptionInfo(uint256)"(
    poolId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    position: BigNumber;
    payDate: BigNumber;
    turnTime: BigNumber;
    owings: BigNumber;
    reward: BigNumber;
    colBals: BigNumber;
    isAdmin: boolean;
    isMember: boolean;
    hasGH: boolean;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: boolean;
    7: boolean;
    8: boolean;
  }>;

  initializeInfo(
    info: {
      position: BigNumberish;
      payDate: BigNumberish;
      turnTime: BigNumberish;
      owings: BigNumberish;
      reward: BigNumberish;
      colBals: BigNumberish;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
    },
    lock: boolean,
    reduceBalance: boolean,
    poolId: BigNumberish,
    value: BigNumberish,
    asset: string,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initializeInfo((uint256,uint256,uint256,uint256,uint256,uint256,bool,bool,bool),bool,bool,uint256,uint256,address,address)"(
    info: {
      position: BigNumberish;
      payDate: BigNumberish;
      turnTime: BigNumberish;
      owings: BigNumberish;
      reward: BigNumberish;
      colBals: BigNumberish;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
    },
    lock: boolean,
    reduceBalance: boolean,
    poolId: BigNumberish,
    value: BigNumberish,
    asset: string,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  manager(overrides?: CallOverrides): Promise<string>;

  "manager()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  rekey(
    newAccount: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "rekey(address)"(
    newAccount: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setStatus(
    poolId: BigNumberish,
    isAdmin: boolean,
    isMember: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setStatus(uint256,bool,bool)"(
    poolId: BigNumberish,
    isAdmin: boolean,
    isMember: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  split(
    poolId: BigNumberish,
    asset: string,
    members: string[],
    closeTo: string,
    unitAmount: BigNumberish,
    _balance: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "split(uint256,address,address[],address,uint256,uint256)"(
    poolId: BigNumberish,
    asset: string,
    members: string[],
    closeTo: string,
    unitAmount: BigNumberish,
    _balance: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  subscriptionInfo(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    position: BigNumber;
    payDate: BigNumber;
    turnTime: BigNumber;
    owings: BigNumber;
    reward: BigNumber;
    colBals: BigNumber;
    isAdmin: boolean;
    isMember: boolean;
    hasGH: boolean;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: boolean;
    7: boolean;
    8: boolean;
  }>;

  "subscriptionInfo(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    position: BigNumber;
    payDate: BigNumber;
    turnTime: BigNumber;
    owings: BigNumber;
    reward: BigNumber;
    colBals: BigNumber;
    isAdmin: boolean;
    isMember: boolean;
    hasGH: boolean;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: boolean;
    7: boolean;
    8: boolean;
  }>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateBalancesInUse(
    asset: string,
    value: BigNumberish,
    reduce: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateBalancesInUse(address,uint256,bool)"(
    asset: string,
    value: BigNumberish,
    reduce: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateTurnTime(
    poolId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateTurnTime(uint256)"(
    poolId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawERC20TokenOnlyOwner(
    erc20Address: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawERC20TokenOnlyOwner(address,uint256)"(
    erc20Address: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawRouterOnly(
    token: string,
    to: string,
    feeTo: string,
    amount: BigNumberish,
    fee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawRouterOnly(address,address,address,uint256,uint256)"(
    token: string,
    to: string,
    feeTo: string,
    amount: BigNumberish,
    fee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    added(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "added(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    approve(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "approve(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    balances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balances(address,uint8)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    clearSubscription(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "clearSubscription(uint256)"(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    depositERC20Token(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "depositERC20Token(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    erc20Balances(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "erc20Balances(address)"(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpendableBalance(
      token: string,
      overrides?: CallOverrides
    ): Promise<{
      _withdrawable: BigNumber;
      _engaged: BigNumber;
      _mostRecent: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    "getSpendableBalance(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<{
      _withdrawable: BigNumber;
      _engaged: BigNumber;
      _mostRecent: BigNumber;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
    }>;

    getSubscriptionInfo(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      position: BigNumber;
      payDate: BigNumber;
      turnTime: BigNumber;
      owings: BigNumber;
      reward: BigNumber;
      colBals: BigNumber;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
      7: boolean;
      8: boolean;
    }>;

    "getSubscriptionInfo(uint256)"(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      position: BigNumber;
      payDate: BigNumber;
      turnTime: BigNumber;
      owings: BigNumber;
      reward: BigNumber;
      colBals: BigNumber;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
      7: boolean;
      8: boolean;
    }>;

    initializeInfo(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "initializeInfo((uint256,uint256,uint256,uint256,uint256,uint256,bool,bool,bool),bool,bool,uint256,uint256,address,address)"(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    manager(overrides?: CallOverrides): Promise<string>;

    "manager()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    rekey(newAccount: string, overrides?: CallOverrides): Promise<boolean>;

    "rekey(address)"(
      newAccount: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setStatus(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "setStatus(uint256,bool,bool)"(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    split(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "split(uint256,address,address[],address,uint256,uint256)"(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    subscriptionInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      position: BigNumber;
      payDate: BigNumber;
      turnTime: BigNumber;
      owings: BigNumber;
      reward: BigNumber;
      colBals: BigNumber;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
      7: boolean;
      8: boolean;
    }>;

    "subscriptionInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      position: BigNumber;
      payDate: BigNumber;
      turnTime: BigNumber;
      owings: BigNumber;
      reward: BigNumber;
      colBals: BigNumber;
      isAdmin: boolean;
      isMember: boolean;
      hasGH: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
      7: boolean;
      8: boolean;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBalancesInUse(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "updateBalancesInUse(address,uint256,bool)"(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateTurnTime(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "updateTurnTime(uint256)"(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    withdrawERC20TokenOnlyOwner(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawERC20TokenOnlyOwner(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawRouterOnly(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "withdrawRouterOnly(address,address,address,uint256,uint256)"(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    AccountLaunched(
      undefined: string | null,
      undefined: string | null
    ): EventFilter;

    BandCreated(undefined: null, undefined: null): EventFilter;

    GetFinanced(undefined: null, undefined: null, undefined: null): EventFilter;

    Joined(undefined: null, undefined: null, undefined: null): EventFilter;

    NewAccount(
      undefined: string | null,
      undefined: string | null,
      undefined: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    Payback(
      undefined: null,
      undefined: null,
      undefined: string | null
    ): EventFilter;

    Rekeyed(undefined: string | null, undefined: string | null): EventFilter;

    RoundUp(undefined: null, undefined: null): EventFilter;
  };

  estimateGas: {
    added(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "added(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balances(address,uint8)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    clearSubscription(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "clearSubscription(uint256)"(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    depositERC20Token(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "depositERC20Token(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    erc20Balances(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "erc20Balances(address)"(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpendableBalance(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSpendableBalance(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSubscriptionInfo(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSubscriptionInfo(uint256)"(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeInfo(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initializeInfo((uint256,uint256,uint256,uint256,uint256,uint256,bool,bool,bool),bool,bool,uint256,uint256,address,address)"(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    "manager()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    rekey(newAccount: string, overrides?: Overrides): Promise<BigNumber>;

    "rekey(address)"(
      newAccount: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setStatus(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setStatus(uint256,bool,bool)"(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    split(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "split(uint256,address,address[],address,uint256,uint256)"(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    subscriptionInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "subscriptionInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateBalancesInUse(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateBalancesInUse(address,uint256,bool)"(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateTurnTime(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateTurnTime(uint256)"(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawERC20TokenOnlyOwner(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawERC20TokenOnlyOwner(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawRouterOnly(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawRouterOnly(address,address,address,uint256,uint256)"(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    added(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "added(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balances(address,uint8)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    clearSubscription(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "clearSubscription(uint256)"(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    depositERC20Token(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "depositERC20Token(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    erc20Balances(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "erc20Balances(address)"(
      erc20Address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSpendableBalance(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSpendableBalance(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubscriptionInfo(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSubscriptionInfo(uint256)"(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeInfo(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initializeInfo((uint256,uint256,uint256,uint256,uint256,uint256,bool,bool,bool),bool,bool,uint256,uint256,address,address)"(
      info: {
        position: BigNumberish;
        payDate: BigNumberish;
        turnTime: BigNumberish;
        owings: BigNumberish;
        reward: BigNumberish;
        colBals: BigNumberish;
        isAdmin: boolean;
        isMember: boolean;
        hasGH: boolean;
      },
      lock: boolean,
      reduceBalance: boolean,
      poolId: BigNumberish,
      value: BigNumberish,
      asset: string,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "manager()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rekey(
      newAccount: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "rekey(address)"(
      newAccount: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setStatus(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setStatus(uint256,bool,bool)"(
      poolId: BigNumberish,
      isAdmin: boolean,
      isMember: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    split(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "split(uint256,address,address[],address,uint256,uint256)"(
      poolId: BigNumberish,
      asset: string,
      members: string[],
      closeTo: string,
      unitAmount: BigNumberish,
      _balance: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    subscriptionInfo(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "subscriptionInfo(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateBalancesInUse(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateBalancesInUse(address,uint256,bool)"(
      asset: string,
      value: BigNumberish,
      reduce: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateTurnTime(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateTurnTime(uint256)"(
      poolId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawERC20TokenOnlyOwner(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawERC20TokenOnlyOwner(address,uint256)"(
      erc20Address: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawRouterOnly(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawRouterOnly(address,address,address,uint256,uint256)"(
      token: string,
      to: string,
      feeTo: string,
      amount: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
