/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import { Contract, ContractTransaction } from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICommonInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "AccountLaunched(address,address)": EventFragment;
    "BandCreated(uint256,tuple)": EventFragment;
    "GetFinanced(uint256,uint256,address)": EventFragment;
    "Joined(uint256,address,uint256)": EventFragment;
    "NewAccount(address,address,uint256)": EventFragment;
    "Payback(uint256,uint256,address)": EventFragment;
    "Rekeyed(address,address)": EventFragment;
    "RoundUp(uint256,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountLaunched"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BandCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GetFinanced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Joined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewAccount"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Payback"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rekeyed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoundUp"): EventFragment;
}

export class ICommon extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICommonInterface;

  functions: {};

  callStatic: {};

  filters: {
    AccountLaunched(
      undefined: string | null,
      undefined: string | null
    ): EventFilter;

    BandCreated(undefined: null, undefined: null): EventFilter;

    GetFinanced(undefined: null, undefined: null, undefined: null): EventFilter;

    Joined(undefined: null, undefined: null, undefined: null): EventFilter;

    NewAccount(
      undefined: string | null,
      undefined: string | null,
      undefined: null
    ): EventFilter;

    Payback(
      undefined: null,
      undefined: null,
      undefined: string | null
    ): EventFilter;

    Rekeyed(undefined: string | null, undefined: string | null): EventFilter;

    RoundUp(undefined: null, undefined: null): EventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
