import Head from 'next/head'
import Homepage from '../components/Homepage'
import styles from '../styles/Home.module.css'
//import { useRouter } from "next/router"
//import Link from "next/link";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Homepage />
        </div>
  )
}
